export enum GATEWAY {
  ZAIN = "ZAIN",
  FIB = "FIB",
}

export enum PAYMENT_STATUS {
  TIMED_OUT = "TIMED_OUT",
  PENDING = "PENDING",
  PAID = "PAID",
  CANCELED = "CANCELED",
  FAILED = "FAILED",
  SETTLED = "SETTLED",
}
